# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

volumes:
  orderer2.superapp.epm.com:
  orderer3.superapp.epm.com:
  orderer4.superapp.epm.com:
  orderer5.superapp.epm.com:

networks:
  byfn:

services:
  orderer2.superapp.epm.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.superapp.epm.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer2.superapp.epm.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer2.superapp.epm.com/tls/:/var/hyperledger/orderer/tls
      - orderer2.superapp.epm.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050

  orderer3.superapp.epm.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.superapp.epm.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer3.superapp.epm.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer3.superapp.epm.com/tls/:/var/hyperledger/orderer/tls
      - orderer3.superapp.epm.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050

  orderer4.superapp.epm.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.superapp.epm.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer4.superapp.epm.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer4.superapp.epm.com/tls/:/var/hyperledger/orderer/tls
      - orderer4.superapp.epm.com:/var/hyperledger/production/orderer
    ports:
      - 10050:7050

  orderer5.superapp.epm.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.superapp.epm.com
    networks:
      - byfn
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer5.superapp.epm.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/superapp.epm.com/orderers/orderer5.superapp.epm.com/tls/:/var/hyperledger/orderer/tls
      - orderer5.superapp.epm.com:/var/hyperledger/production/orderer
    ports:
      - 11050:7050
